default["app"]["directory"] = "/apps"
default["data"]["directory"] = "/datadir"
default["temp"]["directory"] = "/tmp"
default["software"]["multichain"] = "multichain-2.0-beta-1.tar.gz"
default["blockchain"]["name"] = "testchain"
default["blockchain"]["ip"] = "139.180.202.167"
default["blockchain"]["port"] = "2651"